### ISSUE TITLE
Problem with installing the R package

### ISSUE THREAD

**Issue by IvanSilbern** [CamaraLab/RayleighSelection#15]
Dear Developers,

I was attracted by your article in Plos One and wanted to try the approach on some proteomics data. However, I've got a problem when installing the package (s. the error message below). I am using R version 3.5.0 (2018-04-23) on platform: x86_64-w64-mingw32/x64 (64-bit) running under: Windows 10 x64 (build 17134).

Thank you for your help!

Best,
Ivan

`
devtools::install_github("CamaraLab/RayleighSelection")
Downloading GitHub repo CamaraLab/RayleighSelection@master
These packages have more recent versions available.
Which would you like to update?
1: All                               
2: CRAN packages only                
3: None                              
4: igraph (1.2.4.1 -> 1.2.4.2) [CRAN]

Enter one or more numbers, or an empty line to skip updates:

√  checking for file 'C:\Users\IS\AppData\Local\Temp\RtmpENCvNJ\remotes19e88474a1a\CamaraLab-RayleighSelection-4d99000/DESCRIPTION' (516ms)
-  preparing 'RayleighSelection':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (811ms)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'RayleighSelection_0.0.0.9000.tar.gz' (708ms)
   
* installing *source* package 'RayleighSelection' ...
** libs

*** arch - i386
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG  -I"C:/Program Files/R/R-3.5.0/library/Rcpp/include" -I"C:/Program Files/R/R-3.5.0/library/RcppArmadillo/include"     -fopenmp    -O3 -Wno-unused-variable -Wno-unused-function -c RcppExports.cpp -o RcppExports.o
C:/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG  -I"C:/Program Files/R/R-3.5.0/library/Rcpp/include" -I"C:/Program Files/R/R-3.5.0/library/RcppArmadillo/include"     -fopenmp    -O3 -Wno-unused-variable -Wno-unused-function -c adjacency.cpp -o adjacency.o
adjacency.cpp:9:28: error: '>>' should be '> >' within a nested template argument list
 std::vector<std::vector<int>> combo(int N, int K)
                            ^
adjacency.cpp: In function 'std::vector<std::vector<int, std::allocator<int> > > combo(int, int)':
adjacency.cpp:13:30: error: '>>' should be '> >' within a nested template argument list
   std::vector<std::vector<int>> combos;
                              ^
adjacency.cpp: In function 'Rcpp::List adjacencyCpp(Rcpp::List, Rcpp::IntegerVector&)':
adjacency.cpp:86:36: error: '>>' should be '> >' within a nested template argument list
   std::vector<std::pair<int, double>> feature_index_mean;
                                    ^
adjacency.cpp:99:65: error: 'get' is not a member of 'std'
                  (const int& (*)(const std::pair<int, double>&))std::get<0>);
                                                                 ^
adjacency.cpp:99:76: error: expected primary-expression before ')' token
                  (const int& (*)(const std::pair<int, double>&))std::get<0>);
                                                                            ^
adjacency.cpp:161:32: error: '>>' should be '> >' within a nested template argument list
     std::vector<std::vector<int>> edge_idxs = combo(idxs.size(), 2);
                                ^
adjacency.cpp:163:13: error: expected unqualified-id before '&&' token
     for(auto&& e : edge_idxs)
             ^
adjacency.cpp:163:13: error: expected ';' before '&&' token
adjacency.cpp:163:18: error: expected ';' before ':' token
     for(auto&& e : edge_idxs)
                  ^
adjacency.cpp:163:18: error: expected primary-expression before ':' token
adjacency.cpp:163:18: error: expected ')' before ':' token
adjacency.cpp:163:18: error: expected primary-expression before ':' token
adjacency.cpp:163:16: error: label 'e' used but not defined
     for(auto&& e : edge_idxs)
                ^
make: *** [C:/PROGRA~1/R/R-35~1.0/etc/i386/Makeconf:215: adjacency.o] Error 1
ERROR: compilation failed for package 'RayleighSelection'
* removing 'C:/Program Files/R/R-3.5.0/library/RayleighSelection'
In R CMD INSTALL
Error: Failed to install 'RayleighSelection' from GitHub:
installation of package ‘C:/Users/IS/AppData/Local/Temp/RtmpENCvNJ/file19e8164e5246/RayleighSelection_0.0.0.9000.tar.gz’ had non-zero exit status
`

**Comment by ChangLu92** [comment]
Do you have any solution to deal with it? I have the same problem with 

> Dear Developers,
> 
> I was attracted by your article in Plos One and wanted to try the approach on some proteomics data. However, I've got a problem when installing the package (s. the error message below). I am using R version 3.5.0 (2018-04-23) on platform: x86_64-w64-mingw32/x64 (64-bit) running under: Windows 10 x64 (build 17134).
> 
> Thank you for your help!
> 
> Best,
> Ivan
> 
> `
> devtools::install_github("CamaraLab/RayleighSelection")
> Downloading GitHub repo CamaraLab/RayleighSelection@master
> These packages have more recent versions available.
> Which would you like to update?
> 1: All
> 2: CRAN packages only
> 3: None
> 4: igraph (1.2.4.1 -> 1.2.4.2) [CRAN]
> 
> Enter one or more numbers, or an empty line to skip updates:
> 
> √ checking for file 'C:\Users\IS\AppData\Local\Temp\RtmpENCvNJ\remotes19e88474a1a\CamaraLab-RayleighSelection-4d99000/DESCRIPTION' (516ms)
> 
> * preparing 'RayleighSelection':
>   √  checking DESCRIPTION meta-information ...
> * cleaning src
> * checking for LF line-endings in source and make files and shell scripts (811ms)
> * checking for empty or unneeded directories
> * looking to see if a 'data/datalist' file should be added
> * building 'RayleighSelection_0.0.0.9000.tar.gz' (708ms)
> 
> * installing _source_ package 'RayleighSelection' ...
>   ** libs
> 
> *** arch - i386
> C:/Rtools/mingw_32/bin/g++ -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG -I"C:/Program Files/R/R-3.5.0/library/Rcpp/include" -I"C:/Program Files/R/R-3.5.0/library/RcppArmadillo/include" -fopenmp -O3 -Wno-unused-variable -Wno-unused-function -c RcppExports.cpp -o RcppExports.o
> C:/Rtools/mingw_32/bin/g++ -I"C:/PROGRA~1/R/R-35~1.0/include" -DNDEBUG -I"C:/Program Files/R/R-3.5.0/library/Rcpp/include" -I"C:/Program Files/R/R-3.5.0/library/RcppArmadillo/include" -fopenmp -O3 -Wno-unused-variable -Wno-unused-function -c adjacency.cpp -o adjacency.o
> adjacency.cpp:9:28: error: '>>' should be '> >' within a nested template argument list
> std::vector<std::vector> combo(int N, int K)
> ^
> adjacency.cpp: In function 'std::vector<std::vector<int, std::allocator > > combo(int, int)':
> adjacency.cpp:13:30: error: '>>' should be '> >' within a nested template argument list
> std::vector<std::vector> combos;
> ^
> adjacency.cpp: In function 'Rcpp::List adjacencyCpp(Rcpp::List, Rcpp::IntegerVector&)':
> adjacency.cpp:86:36: error: '>>' should be '> >' within a nested template argument list
> std::vector<std::pair<int, double>> feature_index_mean;
> ^
> adjacency.cpp:99:65: error: 'get' is not a member of 'std'
> (const int& (_)(const std::pair<int, double>&))std::get<0>); ^ adjacency.cpp:99:76: error: expected primary-expression before ')' token (const int& (_)(const std::pair<int, double>&))std::get<0>);
> ^
> adjacency.cpp:161:32: error: '>>' should be '> >' within a nested template argument list
> std::vector<std::vector> edge_idxs = combo(idxs.size(), 2);
> ^
> adjacency.cpp:163:13: error: expected unqualified-id before '&&' token
> for(auto&& e : edge_idxs)
> ^
> adjacency.cpp:163:13: error: expected ';' before '&&' token
> adjacency.cpp:163:18: error: expected ';' before ':' token
> for(auto&& e : edge_idxs)
> ^
> adjacency.cpp:163:18: error: expected primary-expression before ':' token
> adjacency.cpp:163:18: error: expected ')' before ':' token
> adjacency.cpp:163:18: error: expected primary-expression before ':' token
> adjacency.cpp:163:16: error: label 'e' used but not defined
> for(auto&& e : edge_idxs)
> ^
> make: *** [C:/PROGRA~1/R/R-35~1.0/etc/i386/Makeconf:215: adjacency.o] Error 1
> ERROR: compilation failed for package 'RayleighSelection'
> 
> * removing 'C:/Program Files/R/R-3.5.0/library/RayleighSelection'
>   In R CMD INSTALL
>   Error: Failed to install 'RayleighSelection' from GitHub:
>   installation of package ‘C:/Users/IS/AppData/Local/Temp/RtmpENCvNJ/file19e8164e5246/RayleighSelection_0.0.0.9000.tar.gz’ had non-zero exit status
>   `

Do you find any solution to deal with it? I have the same problem as you.

**Comment by IvanSilbern** [comment]
> Do you find any solution to deal with it? I have the same problem as you.

No, I do not. I've tried to reinstall Rcpp, but it did not help.

Best,
Ivan

**Comment by syamajala** [comment]
It looks like the compiler does not know the code is c++11. I think CXX_STD
needs to be undocumented in Makevars and Makevars.win?

**Comment by govekk** [comment]
Thanks for bringing this up! It looks like this is the case for anyone trying to install on Windows. I agree that it seems to be a problem with compiling this version of C++ on Windows, but tried the fix suggested by @syamajala and still got the same error.

While we look into this, I’ve created a Docker image that runs an RStudio server with RayleighSelection installed, which can be run via PowerShell using Docker for Windows: https://hub.docker.com/r/camaralab/rayleigh-selection.

**Comment by govekk** [comment]
I must have been doing something wrong before, because I just reinstalled it from scratch with the fix suggested by @syamajala and it worked this time! I've moved that change to master, so please let me know if you are still running into the same problem.

On Windows, you will not be able to parallelize the computation of the Laplacian score using the mclapply function. So if you have a large dataset, I would still suggest running RayleighSelection through the provided Docker image.
